export const DOG_LIST_REQUEST = 'DOG_LIST_REQUEST'
export const DOG_LIST_SUCCESS = 'DOG_LIST_SUCCESS'
export const DOG_LIST_FAIL = 'DOG_LIST_FAIL'

export const DOG_DETAILS_REQUEST = 'DOG_DETAILS_REQUEST'
export const DOG_DETAILS_SUCCESS = 'DOG_DETAILS_SUCCESS'
export const DOG_DETAILS_FAIL = 'DOG_DETAILS_FAIL'

export const DOG_DELETE_REQUEST = 'DOG_DELETE_REQUEST'
export const DOG_DELETE_SUCCESS = 'DOG_DELETE_SUCCESS'
export const DOG_DELETE_FAIL = 'DOG_DELETE_FAIL'

export const DOG_CREATE_REQUEST = 'DOG_CREATE_REQUEST'
export const DOG_CREATE_SUCCESS = 'DOG_CREATE_SUCCESS'
export const DOG_CREATE_FAIL = 'DOG_CREATE_FAIL'
export const DOG_CREATE_RESET = 'DOG_CREATE_RESET'

export const DOG_UPDATE_REQUEST = 'DOG_UPDATE_REQUEST'
export const DOG_UPDATE_SUCCESS = 'DOG_UPDATE_SUCCESS'
export const DOG_UPDATE_FAIL = 'DOG_UPDATE_FAIL'
export const DOG_UPDATE_RESET = 'DOG_UPDATE_RESET'

export const DOG_TOP_REQUEST = 'DOG_TOP_REQUEST'
export const DOG_TOP_SUCCESS = 'DOG_TOP_SUCCESS'
export const DOG_TOP_FAIL = 'DOG_TOP_FAIL'
