export const USER_ADD_FAVOURITE_REQUEST = 'USER_ADD_FAVOURITE_REQUEST'
export const USER_ADD_FAVOURITE_SUCCESS = 'USER_ADD_FAVOURITE_SUCCESS'
export const USER_ADD_FAVOURITE_FAIL = 'USER_ADD_FAVOURITE_FAIL'

export const USER_DELETE_FAVOURITE_REQUEST = 'USER_DELETE_FAVOURITE_REQUEST'
export const USER_DELETE_FAVOURITE_SUCCESS = 'USER_DELETE_FAVOURITE_SUCCESS'
export const USER_DELETE_FAVOURITE_FAIL = 'USER_DELETE_FAVOURITE_FAIL'

export const FAVOURITE_DOG_LIST_REQUEST = 'FAVOURITE_DOG_LIST_REQUEST'
export const FAVOURITE_DOG_LIST_SUCCESS = 'FAVOURITE_DOG_LIST_SUCCESS'
export const FAVOURITE_DOG_LIST_FAIL = 'FAVOURITE_DOG_LIST_FAIL'

export const UPDATE_FAVOURITE_REQUEST = 'UPDATE_FAVOURITE_REQUEST'
export const UPDATE_FAVOURITE_SUCCESS = 'UPDATE_FAVOURITE_SUCCESS'
export const UPDATE_FAVOURITE_FAIL = 'UPDATE_FAVOURITE_FAIL'